In [29]:
import tensorflow as tf
from tensorflow import keras
import matplotlib.pyplot as plt
%matplotlib inline
import numpy as np

In [30]:
(X_train, y_train) , (X_test, y_test) = keras.datasets.mnist.load_data()

In [31]:
len(X_train)

60000

In [32]:
len(X_test)

10000

In [33]:
X_train[0].shape

(28, 28)

In [34]:
X_train[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [35]:
plt.matshow(X_train[1])

In [36]:
y_train[2]

4

In [37]:
y_train[:5]

array([5, 0, 4, 1, 9], dtype=uint8)

In [38]:
X_train.shape

(60000, 28, 28)

In [39]:
#scaling : it is a technique that improves the accuracy of machine lerning model
X_train=X_train/255
X_test=X_test/255

In [40]:
#flattening the dataset
X_train_flattened =X_train.reshape(len(X_train),28*28)
X_test_flattened = X_test.reshape(len(X_test),28*28)
X_train_flattened.shape

(60000, 784)

In [41]:
y_train[1]

0

In [42]:
X_train_flattened[1]

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [43]:
model = keras.Sequential([
    keras.layers.Dense(10,input_shape=(784,),activation = 'sigmoid')
])

model.compile(
    optimizer='adam',
    loss='sparse_categorical_crossentropy',
    metrics=['accuracy']
)

model.fit(X_train_flattened,y_train,epochs=5)

Epoch 1/5


c:\Desktop\Sam's Python\.conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


1875/1875 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - accuracy: 0.8118 - loss: 0.7232
Epoch 2/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9156 - loss: 0.3030
Epoch 3/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9214 - loss: 0.2814
Epoch 4/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9222 - loss: 0.2720
Epoch 5/5
1875/1875 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - accuracy: 0.9256 - loss: 0.2674


In [44]:
model.evaluate(X_test_flattened,y_test)

313/313 ━━━━━━━━━━━━━━━━━━━━ 1s 1ms/step - accuracy: 0.9169 - loss: 0.3027


[0.2665719985961914, 0.9279000163078308]

In [45]:
plt.matshow(X_test[0])

In [46]:
y_predicted = model.predict(X_test_flattened)
y_predicted[1]
#we will get an array of scores of 10 values as in like each of the 10 output we had

313/313 ━━━━━━━━━━━━━━━━━━━━ 0s 984us/step


array([2.7165455e-01, 3.2746019e-03, 9.9965370e-01, 2.7223405e-01,
       2.2828549e-10, 8.4624177e-01, 9.1143119e-01, 5.6897683e-13,
       1.2739529e-01, 1.5822504e-09], dtype=float32)

In [47]:
np.argmax(y_predicted[1])

2

In [48]:
y_predicted_lables  =[np.argmax(i) for i in y_predicted]
y_predicted_lables[:5]

[7, 2, 1, 0, 4]

In [49]:
cm = tf.math.confusion_matrix(labels=y_test,predictions=y_predicted_lables)
cm

<tf.Tensor: shape=(10, 10), dtype=int32, numpy=
array([[ 963,    0,    2,    2,    0,    4,    6,    2,    1,    0],
       [   0, 1118,    3,    2,    0,    1,    4,    2,    5,    0],
       [   4,    7,  944,   15,    6,    2,   11,    9,   29,    5],
       [   2,    0,   25,  919,    0,   26,    2,   10,   19,    7],
       [   2,    1,    9,    2,  896,    0,    9,    5,   10,   48],
       [   9,    2,    6,   31,    7,  787,   12,    4,   28,    6],
       [   9,    3,    8,    1,    7,   12,  913,    2,    3,    0],
       [   1,    7,   25,    8,    5,    1,    0,  942,    1,   38],
       [   7,    9,    8,   24,    9,   30,    9,    9,  859,   10],
       [  11,    7,    1,   11,   16,    7,    0,   14,    4,  938]])>

In [50]:
import seaborn as sn
plt.figure(figsize = (10,7))
sn.heatmap(cm, annot=True, fmt='d')
plt.xlabel('Predicted')
plt.ylabel('Truth')

ModuleNotFoundError: No module named 'seaborn'